"""create_tax_tables

Revision ID: 6e53c00a09f4
Revises: 9bd655dd20b4
Create Date: 2026-06-26 11:27:58.146431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e53c00a09f4'
down_revision: Union[str, Sequence[str], None] = '9bd655dd20b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('einvoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_number', sa.String(length=20), nullable=False),
    sa.Column('invoice_series', sa.String(length=10), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('invoice_type', sa.String(length=20), nullable=True),
    sa.Column('seller_tax_code', sa.String(length=15), nullable=False),
    sa.Column('seller_name', sa.String(length=300), nullable=False),
    sa.Column('seller_address', sa.String(length=500), nullable=True),
    sa.Column('buyer_tax_code', sa.String(length=15), nullable=True),
    sa.Column('buyer_name', sa.String(length=300), nullable=True),
    sa.Column('buyer_address', sa.String(length=500), nullable=True),
    sa.Column('buyer_id', sa.String(length=50), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'SIGNED', 'SENT', 'CANCELLED', 'REPLACED', 'ADJUSTED', 'ERROR', name='invoicestatusdb'), nullable=False),
    sa.Column('verification_code', sa.String(length=50), nullable=True),
    sa.Column('gdt_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('signed_file_url', sa.String(length=500), nullable=True),
    sa.Column('digital_signature', sa.Text(), nullable=True),
    sa.Column('adjustment_ref_id', sa.Integer(), nullable=True),
    sa.Column('adjustment_type', sa.String(length=20), nullable=True),
    sa.Column('adjustment_reason', sa.String(length=500), nullable=True),
    sa.Column('original_invoice_ref', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_declarations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tax_type', sa.Enum('VAT_DEDUCTION', 'VAT_DIRECT', 'CIT', 'PIT', 'PIT_FINALIZATION', 'LICENSE', 'FOREIGN_CONTRACTOR', 'PERSONAL_RENTAL', 'RESOURCE', 'IMPORT_EXPORT', 'ENVIRONMENTAL', 'PROPERTY', 'OTHER', name='taxtypedb'), nullable=False),
    sa.Column('declaration_type', sa.String(length=20), nullable=False),
    sa.Column('form_code', sa.String(length=20), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('period_quarter', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CALCULATED', 'SUBMITTED', 'ACCEPTED', 'REJECTED', 'AMENDED', 'CANCELLED', name='declarationstatusdb'), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_tax', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_deduction', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_exemption', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_payable', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('previous_adjustment', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('late_interest', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('penalty', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_payable', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('submission_deadline', sa.Date(), nullable=True),
    sa.Column('submitted_date', sa.Date(), nullable=True),
    sa.Column('accepted_date', sa.Date(), nullable=True),
    sa.Column('gdt_reference', sa.String(length=100), nullable=True),
    sa.Column('gdt_error_code', sa.String(length=50), nullable=True),
    sa.Column('etax_submission_id', sa.String(length=100), nullable=True),
    sa.Column('submission_method', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_incentives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tax_type', sa.Enum('VAT_DEDUCTION', 'VAT_DIRECT', 'CIT', 'PIT', 'PIT_FINALIZATION', 'LICENSE', 'FOREIGN_CONTRACTOR', 'PERSONAL_RENTAL', 'RESOURCE', 'IMPORT_EXPORT', 'ENVIRONMENTAL', 'PROPERTY', 'OTHER', name='taxtypedb'), nullable=False),
    sa.Column('incentive_type', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('legal_basis', sa.String(length=200), nullable=False),
    sa.Column('rate_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_percentage', sa.Boolean(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('max_duration_months', sa.Integer(), nullable=True),
    sa.Column('eligibility_condition', sa.Text(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tax_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tax_type', sa.Enum('VAT_DEDUCTION', 'VAT_DIRECT', 'CIT', 'PIT', 'PIT_FINALIZATION', 'LICENSE', 'FOREIGN_CONTRACTOR', 'PERSONAL_RENTAL', 'RESOURCE', 'IMPORT_EXPORT', 'ENVIRONMENTAL', 'PROPERTY', 'OTHER', name='taxtypedb'), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('period_quarter', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('reminder_days_before', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_adjustments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_declaration_id', sa.Integer(), nullable=False),
    sa.Column('supplemental_declaration_id', sa.Integer(), nullable=True),
    sa.Column('adjustment_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('adjusted_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('late_interest', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('penalty', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['original_declaration_id'], ['tax_declarations.id'], ),
    sa.ForeignKeyConstraint(['supplemental_declaration_id'], ['tax_declarations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('declaration_id', sa.Integer(), nullable=False),
    sa.Column('line_code', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_calculated', sa.Boolean(), nullable=True),
    sa.Column('parent_line_code', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['declaration_id'], ['tax_declarations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('declaration_id', sa.Integer(), nullable=False),
    sa.Column('tax_type', sa.Enum('VAT_DEDUCTION', 'VAT_DIRECT', 'CIT', 'PIT', 'PIT_FINALIZATION', 'LICENSE', 'FOREIGN_CONTRACTOR', 'PERSONAL_RENTAL', 'RESOURCE', 'IMPORT_EXPORT', 'ENVIRONMENTAL', 'PROPERTY', 'OTHER', name='taxtypedb'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('budget_account', sa.String(length=10), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'OVERDUE', 'REFUNDED', 'PARTIAL', name='taxpaymentstatusdb'), nullable=False),
    sa.Column('gdt_payment_code', sa.String(length=100), nullable=True),
    sa.Column('bank_reference', sa.String(length=100), nullable=True),
    sa.Column('penalty_interest', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['declaration_id'], ['tax_declarations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_payments')
    op.drop_table('tax_lines')
    op.drop_table('tax_adjustments')
    op.drop_table('tax_schedules')
    op.drop_table('tax_incentives')
    op.drop_table('tax_declarations')
    op.drop_table('einvoices')
    # ### end Alembic commands ###
