"""create_chart_of_accounts

Revision ID: 9bd655dd20b4
Revises: 
Create Date: 2026-06-26 10:43:36.705003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd655dd20b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_of_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('regime', sa.Enum('TT99_2025', 'TT133_2016', name='accountingregime'), nullable=False),
    sa.Column('vas_compliant', sa.Boolean(), nullable=False),
    sa.Column('drcr_direction', sa.String(length=10), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CLOSED', name='accountstatus'), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('parent_code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', ['code'], unique=True)
    op.create_foreign_key('fk_parent_code', 'chart_of_accounts', 'chart_of_accounts',
                          ['parent_code'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_parent_code', 'chart_of_accounts', type_='foreignkey')
    op.drop_index(op.f('ix_chart_of_accounts_code'), table_name='chart_of_accounts')
    op.drop_table('chart_of_accounts')
    # ### end Alembic commands ###
