export enum SlsCustomerStatus { active = "active", inactive = "inactive", blocked = "blocked", suspended = "suspended", pending = "pending" }
export enum SlsCustomerType { individual = "individual", company = "company", government = "government", foreign = "foreign", vip = "vip", wholesale = "wholesale", retail = "retail", internal = "internal" }
export enum SlsCustomerCategory { standard = "standard", silver = "silver", gold = "gold", platinum = "platinum", diamond = "diamond", corporate = "corporate", sme = "sme", franchise = "franchise" }
export enum SlsPriceGroup { groupA = "group_a", groupB = "group_b", groupC = "group_c", groupD = "group_d", retail = "retail", wholesale = "wholesale", special = "special" }
export enum SlsDiscountGroup { none = "none", standard = "standard", preferred = "preferred", vip = "vip", staff = "staff", promotional = "promotional" }
export enum SlsOrderStatus { draft = "draft", pendingApproval = "pending_approval", approved = "approved", confirmed = "confirmed", processing = "processing", partlyDelivered = "partly_delivered", fullyDelivered = "fully_delivered", partlyInvoiced = "partly_invoiced", fullyInvoiced = "fully_invoiced", partlyPaid = "partly_paid", fullyPaid = "fully_paid", completed = "completed", cancelled = "cancelled", onHold = "on_hold", returned = "returned" }
export enum SlsOrderType { standard = "standard", pos = "pos", online = "online", marketplace = "marketplace", wholesale = "wholesale", b2b = "b2b", recurring = "recurring", rush = "rush", preOrder = "pre_order", backorder = "backorder", dropShipment = "drop_shipment", exchange = "exchange", gift = "gift" }
export enum SlsOrderSource { pos = "pos", retail = "retail", online = "online", marketplace = "marketplace", mobileApp = "mobile_app", callCenter = "call_center", socialCommerce = "social_commerce", b2bPortal = "b2b_portal", wholesalePortal = "wholesale_portal", api = "api", manual = "manual", import_ = "import" }
export enum SlsQuotationStatus { draft = "draft", sent = "sent", accepted = "accepted", rejected = "rejected", expired = "expired", converted = "converted", cancelled = "cancelled", revised = "revised" }
export enum SlsDeliveryStatus { draft = "draft", picking = "picking", packed = "packed", shipped = "shipped", inTransit = "in_transit", delivered = "delivered", partlyDelivered = "partly_delivered", deliveryFailed = "delivery_failed", returned = "returned", cancelled = "cancelled", confirmed = "confirmed" }
export enum SlsInvoiceStatus { draft = "draft", issued = "issued", approved = "approved", posted = "posted", partiallyPaid = "partially_paid", fullyPaid = "fully_paid", cancelled = "cancelled", replaced = "replaced", adjusted = "adjusted", debitNote = "debit_note", creditNote = "credit_note", reversed = "reversed" }
export enum SlsInvoiceType { salesInvoice = "sales_invoice", debitNote = "debit_note", creditNote = "credit_note", adjustment = "adjustment", replacement = "replacement", prepayment = "prepayment", final = "final" }
export enum SlsReturnStatus { draft = "draft", pendingApproval = "pending_approval", approved = "approved", received = "received", inspected = "inspected", partlyRefunded = "partly_refunded", fullyRefunded = "fully_refunded", rejected = "rejected", cancelled = "cancelled", completed = "completed", exchanged = "exchanged" }
export enum SlsReturnReason { defective = "defective", wrongItem = "wrong_item", expired = "expired", damaged = "damaged", customerChangeMind = "customer_change_mind", qualityIssue = "quality_issue", warranty = "warranty", overDelivery = "over_delivery", duplicate = "duplicate", other = "other" }
export enum SlsPaymentStatus { pending = "pending", partiallyPaid = "partially_paid", fullyPaid = "fully_paid", overpaid = "overpaid", refunded = "refunded", cancelled = "cancelled" }
export enum SlsPaymentMethod { cash = "cash", bankTransfer = "bank_transfer", qrPayment = "qr_payment", creditCard = "credit_card", debitCard = "debit_card", eWallet = "e_wallet", giftCard = "gift_card", storeCredit = "store_credit", voucher = "voucher", mixed = "mixed", split = "split", cod = "cod", installment = "installment", other = "other" }
export enum SlsPromotionType { discountPercentage = "discount_percentage", discountAmount = "discount_amount", buyXGetY = "buy_x_get_y", bundle = "bundle", combo = "combo", mixMatch = "mix_match", flashSale = "flash_sale", loyalty = "loyalty", birthday = "birthday", seasonal = "seasonal", clearance = "clearance", freeShipping = "free_shipping", giftWithPurchase = "gift_with_purchase", coupon = "coupon", voucher = "voucher", tiered = "tiered", volume = "volume", campaign = "campaign" }
export enum SlsPromotionStatus { draft = "draft", scheduled = "scheduled", active = "active", paused = "paused", expired = "expired", cancelled = "cancelled", completed = "completed" }
export enum SlsCouponStatus { active = "active", used = "used", expired = "expired", cancelled = "cancelled", suspended = "suspended" }
export enum SlsGiftCardStatus { active = "active", partiallyUsed = "partially_used", fullyUsed = "fully_used", expired = "expired", lost = "lost", stolen = "stolen", cancelled = "cancelled" }
export enum SlsLoyaltyTier { bronze = "bronze", silver = "silver", gold = "gold", platinum = "platinum", diamond = "diamond", elite = "elite" }
export enum SlsLoyaltyStatus { active = "active", inactive = "inactive", suspended = "suspended", closed = "closed" }
export enum SlsMembershipStatus { pending = "pending", active = "active", suspended = "suspended", cancelled = "cancelled", expired = "expired" }
export enum SlsReservationStatus { pending = "pending", confirmed = "confirmed", allocated = "allocated", picked = "picked", shipped = "shipped", cancelled = "cancelled", expired = "expired", partiallyFulfilled = "partially_fulfilled", fulfilled = "fulfilled" }
export enum SlsDiscountType { percentage = "percentage", fixedAmount = "fixed_amount", freeItem = "free_item", freeShipping = "free_shipping", bundle = "bundle", tiered = "tiered" }
export enum SlsDiscountApplication { line = "line", header = "header", shipping = "shipping", tax = "tax" }
